### PR TITLE
autocomplete

### PR DESCRIPTION
**Pull request by brucelane**
autocomplete proposition

### CODE REVIEW

**Comment by ojack** [comment]
Hi @brucelane --
I am not sure how to use the autocomplete function! are there instructions somewhere? 

so sorry for the delay with this!

**Comment by brucelane** [comment]
Hi @ojack , 
Try this: type mr and press Ctrl+Space!

**Comment by ojack** [comment]
I think autocomplete is great but the specific choices here seem arbitrary! It would be great to make this code more generalizable so that a user could configure the autocomplete. For the time being, we can go ahead and add this as is; however, I think the autocomplete should be in a separate file autocomplete.js because it is very separate from the editor.js functionality.

**Comment by brucelane** [comment]
I agree

**Comment by brucelane** [comment]
Hi @ojack I'm in Berlin this week and saturday there is Creative Coding Berlin Jam, I will try to work to this feature. May be we can meet?

**Comment by brucelane** [comment]
nevermind...

**Pull request closed without merging**
